# Generated by Django 2.1.2 on 2018-10-18 18:09

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20181018_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='country',
            new_name='user_country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_city',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='user_country', chained_model_field='country', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.City'),
        ),
    ]
